name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install pkg globally
      run: npm install -g pkg
      
    - name: Build binaries
      run: |
        mkdir -p dist
        pkg cli/index.js \
          --targets node18-linux-x64,node18-macos-x64,node18-win-x64 \
          --out-path dist \
          --compress GZip
          
    - name: Rename binaries
      run: |
        cd dist
        mv index-linux p2p-transfer-linux-x64 || true
        mv index-macos p2p-transfer-macos-x64 || true
        mv index-win.exe p2p-transfer-windows-x64.exe || true
        ls -la
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: p2p-transfer-binaries
        path: dist/*
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/p2p-transfer-linux-x64
          dist/p2p-transfer-macos-x64
          dist/p2p-transfer-windows-x64.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}